# Header
menu:
  Home: /
  Archives: /archives
  Induction: /induction
  Gallery: /gallery
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
# sidebar: left
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png
weibo: https://weibo.com/wangcch
github: https://github.com/wangcch
email: mailto:ci713@qq.com
